[desktop]
[[database]]
engine=postgresql_psycopg2
host=postgres-hue
port=5432
user=hue
password=huepassword
name=hue_db

[hadoop]
[[hdfs_clusters]]
[[[default]]]
fs_defaultfs=hdfs://namenode:9000
webhdfs_url=http://namenode:9870/webhdfs/v1

[beeswax]
# Obligatoire
hive_server_host=hive-server2
hive_server_port=10000

# Très utile en Docker
hive_conf_dir=/etc/hive/conf
server_connect_timeout=120
# Option pour forcer le rafraîchissement
# query_settings={\"hive.execution.engine\":\"tez\"}

[notebook]
[[interpreters]]
[[[hive]]]
name=Hive
interface=hiveserver2
options='{"url": "http://hive-server2:10000", "driver": "hive"}'
